#!/bin/zsh

setopt EXTENDED_GLOB

for rcfile in ${ZDOTDIR:-$HOME}/.zprezto/runcoms/z*; do
    dotfile="$HOME/."$(basename $rcfile)
    if [ -e "$dotfile" ]; then
	mv -f "$dotfile" "$dotfile.bak"
    fi
    ln -s "$rcfile" "$dotfile"
done

