#!/bin/zsh

setopt EXTENDED_GLOB

for rcfile in ${ZDOTDIR:-$HOME}/.zprezto/runcoms/z*; do
    dotfile="$HOME/."$(basename $rcfile)
    [[ -e "$dotfile" ]] && mv -f "$dotfile" "$dotfile.bak"
    ln -s "$rcfile" "$dotfile"
done

